name: consultorio_terapeutico_gestaltico
description: App para reservas personales.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=2.18.1 <3.0.0'


dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.5
  firebase_core_platform_interface: ^4.5.3
  shared_preferences: ^2.0.17
  image_picker: ^0.8.6+1
  provider: ^6.0.5
  fluttericon: ^2.0.0
  font_awesome_flutter: ^10.3.0
  lazy_load_scrollview: ^1.3.0
  intl: any
  firebase_storage: ^11.0.10
  file_picker: ^5.2.5
  faker: ^2.1.0
  cloud_firestore: ^4.3.1
  firebase_messaging: ^14.2.6
  flutter_local_notifications: ^9.0.0
  flutter_localization: ^0.1.9
  flutter_localizations: # Add this line
    sdk: flutter         # Add this line
  firebase_core: ^2.7.0
  cupertino_icons: ^1.0.2
  firebase_analytics: ^10.1.5
  firebase_database: ^10.0.16
  change_app_package_name: ^1.1.0
  url_launcher: ^6.1.10
  flutter_rating_bar: ^4.0.1
  mailer: ^6.0.1
  vibration: ^1.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true
  assets:
    - assets/




